name: Cppcheck

on:
  push:
    branches: [ nimish ]
  pull_request:
    branches: [ nimish ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: sudo apt-get install cppcheck    
    - name: Static Analysis
      run: cppcheck --enable=all Project
